(ns housewaretrade.render-html
  "Build-time HTML renderer for `docs/samples/operator-console.html`.

  Closes flagship checklist item 2 for this repo: `docs/samples/
  operator-console.html` previously existed as a HAND-WRITTEN page with
  no generator behind it -- and it showed at least one field that is
  NOT in this repo's seed data (it captioned `ho-8` as a 'portable
  space heater'; `housewaretrade.store/demo-data` only ever says
  `:product-category :small-appliance`, `:sku \"HG-SKU-10008\"`). This
  namespace replaces that page with one generated by driving the REAL
  actor stack -- `housewaretrade.operation` (a langgraph-clj
  StateGraph) -> `housewaretrade.governor` -> `housewaretrade.store` --
  so every id, counterparty, SKU, jurisdiction, dispatch/invoice number
  and disposition on the page is actual governor/store output.

  The scenario below is adapted from this repo's OWN demo driver
  `housewaretrade.sim` (`clojure -M:dev:run`), which was read first to
  learn the real seeded order ids (`ho-1`..`ho-8`) and the real request
  shapes. It is trimmed to what a console needs to show and extended
  with one case `sim` does not exercise (`ho-2` at `:delivery/dispatch`,
  which reaches the governor's `:evidence-incomplete` check), so that
  ALL NINE of this governor's HARD rules appear on the page.

  Determinism: no timestamps, no randomness, no reliance on hash-map
  iteration order in the page content. Orders come back from
  `store/all-household-orders` already sorted by `:id`; the ledger is an
  append-only vector in the order this scenario produced it; every other
  collection rendered here is either that ledger, an explicit vector
  literal, or a `sort`ed distinct set. Verify with two consecutive runs
  into a scratch directory and `cmp`.

  Usage: `clojure -M:dev:render-html [out-file]`
  (default `docs/samples/operator-console.html`)."
  (:require [jp-go-dds.skin]
            [kotoba.lang.text :as str]
            [housewaretrade.facts :as facts]
            [housewaretrade.governor :as governor]
            [housewaretrade.phase :as phase]
            [housewaretrade.store :as store]
            [housewaretrade.operation :as op]
            [langgraph.graph :as g]))

(def ^:private operator
  "The same operator context this repo's own `housewaretrade.sim` uses
  -- phase 3 (`supervised-auto`), the most permissive phase this actor
  has, so that every hold on the page is the GOVERNOR's doing and not a
  phase-disabled artifact."
  {:actor-id "op-1" :actor-role :trading-supervisor :phase 3})

(def ^:private ^:dynamic *audit*
  "Collector for the run's audit channel. `langgraph.graph/run*` returns
  `{:state :events :status :frontier}` and the actor's `:audit` channel
  lives on `:state`; only the `:commit`/`:hold` nodes copy anything from
  there into the store's ledger, so the `:approval-granted` facts exist
  ONLY here. The console's approver-attribution section is a join
  between these facts and what the SSoT actually holds -- see
  `approver-on-record`."
  nil)

(def ^:private ^:dynamic *db*
  "The store `run-demo!` is driving, so `approve!` can measure what a
  single approval actually wrote to it."
  nil)

(defn- collect! [r]
  (when *audit* (swap! *audit* into (:audit (:state r))))
  r)

(defn- exec! [actor tid request]
  (collect! (g/run* actor {:request request :context operator} {:thread-id tid})))

;; --- did the approver reach the SSoT? (measured, never asserted) -----
;;
;; A known, real scaffold defect in this actor, rendered honestly rather
;; than papered over: `housewaretrade.operation`'s `:request-approval`
;; node attaches the approver to the record under `:payload`
;; (`(assoc (:value proposal) :approved-by (:by approval))`), but
;; `housewaretrade.store/commit-record!` only READS `:payload` for the
;; `:safety-assessment/set` effect. `:order/upsert` writes `:value`
;; (which carries no approver) and `:order/mark-dispatched` /
;; `:order/mark-invoiced` derive their patch from the store itself and
;; read neither.
;;
;; Rather than encode that reasoning as a claim on the page, `approve!`
;; MEASURES it: it snapshots the whole store before and after each
;; approval, and searches only the artifacts that approval actually
;; changed. That distinction matters -- a `:delivery/dispatch` approval
;; for `ho-1` runs against a store whose `ho-1` assessment ALREADY
;; carries `:approved-by "op-1"` (put there by the earlier
;; `:safety/verify` approval), so a naive point-in-time probe would
;; credit the dispatch with an attribution it never made.

(def ^:private approver-key-re #"(?i)approv")

(defn- approver-in
  "The first approval-ish [key value] pair anywhere inside `v`, or nil.
  Handles both keyword-keyed store maps and the string-keyed registry
  drafts; descends in sorted key order so the answer never depends on
  hash-map iteration order."
  [v]
  (cond
    (map? v) (let [sorted (sort-by (comp str key) v)]
               (or (first (filter (fn [[k _]] (re-find approver-key-re (str k))) sorted))
                   (some (comp approver-in val) sorted)))
    (sequential? v) (some approver-in v)
    :else nil))

(defn- store-snapshot []
  (let [orders (store/all-household-orders *db*)]
    {:orders (into {} (map (juxt :id identity) orders))
     :assessments (into {} (map (juxt :id #(store/assessment-of *db* (:id %))) orders))
     :drafts (vec (concat (store/dispatch-history *db*) (store/invoice-history *db*)))}))

(defn- approver-landed
  "Where -- if anywhere -- an approver appears in the SSoT data that
  changed between `before` and `after`. `{:where .. :key .. :value ..}`
  or nil."
  [before after]
  (let [changed (concat
                 (for [[id m] (sort-by key (:assessments after))
                       :when (and (some? m) (not= m (get-in before [:assessments id])))]
                   [(str "safety assessment for " id) m])
                 (for [[id m] (sort-by key (:orders after))
                       :when (not= m (get-in before [:orders id]))]
                   [(str "household-order record " id) m])
                 (for [r (drop (count (:drafts before)) (:drafts after))]
                   [(str "registry draft " (get r "record_id")) r]))]
    (some (fn [[where m]]
            (when-let [[k v] (approver-in m)]
              {:where where :key (str k) :value v}))
          changed)))

(defn- approve! [actor tid]
  (let [before (store-snapshot)
        r (g/run* actor {:approval {:status :approved :by (:actor-id operator)}}
                  {:thread-id tid :resume? true})
        landed (approver-landed before (store-snapshot))]
    (when *audit*
      (swap! *audit* into
             (mapv (fn [f]
                     (cond-> f
                       (= :approval-granted (:t f)) (assoc :approver-landed landed)))
                   (:audit (:state r)))))
    r))

(defn- verify+approve!
  "`:safety/verify` escalates at every phase (it is a write op that is
  never in any phase's `:auto` set), so the human trading supervisor
  approves it. Needed before any `:delivery/dispatch` can clear the
  governor's `:evidence-incomplete` check."
  [actor ho-id]
  (let [tid (str ho-id "-verify")]
    (exec! actor tid {:op :safety/verify :subject ho-id})
    (approve! actor tid)))

(defn- dispatch+approve! [actor ho-id]
  (let [tid (str ho-id "-dispatch")]
    (exec! actor tid {:op :delivery/dispatch :subject ho-id})
    (approve! actor tid)))

(defn run-demo!
  "Runs a fresh seeded store through a scenario that reaches every
  disposition this actor can produce and exercises ALL NINE of
  `housewaretrade.governor`'s HARD rules, one order per failure mode:

    - `ho-1` (cookware, a general household good) clears a full
      lifecycle: intake (auto-commits at phase 3 -- no capital risk),
      safety verification (approved), physical dispatch (approved --
      `:delivery/dispatch` is never auto-eligible at any phase) and
      invoice settlement (approved). Re-running its dispatch and its
      settlement at the end HARD-holds on `:already-dispatched` /
      `:already-invoiced`.
    - `ho-2` (jurisdiction `ATL`, deliberately absent from
      `housewaretrade.facts/catalog`) HARD-holds its safety
      verification on `:no-spec-basis`, and -- because that hold means
      no assessment was ever committed for it -- HARD-holds a
      subsequent dispatch on `:evidence-incomplete`.
    - `ho-3` HARD-holds dispatch on `:credit-uncleared`.
    - `ho-4` HARD-holds dispatch on `:contract-missing`.
    - `ho-5` HARD-holds dispatch on
      `:counterparty-sanctions-flag-unresolved`.
    - `ho-6` (a toy, a children's product, WITH both evidentiary arms of
      its Children's Product Certificate on file) dispatches and
      settles CLEANLY -- proving the CPC check is satisfiable, not a
      trap.
    - `ho-7` (a toy, lab-tested but with no CPC actually on file)
      HARD-holds dispatch on `:childrens-product-certificate-missing`.
    - `ho-8` (an active, unresolved recall) HARD-holds dispatch on
      `:active-recall-unresolved`; a compliance officer then records the
      recall's resolution through a plain `:order/intake` patch, and the
      SAME order/SKU dispatches cleanly -- the post-hoc recall lifecycle
      proof this vertical's own regulatory mechanic (CPSA §15(b)) calls
      for.

  Returns `{:db store :audit [fact ...]}`. Every value the page renders
  is read back out of that store, except the `:approval-granted` facts,
  which only ever exist on the run's audit channel (see `*audit*`)."
  []
  (let [db (store/seed-db)]
   (binding [*audit* (atom []) *db* db]
   (let [actor (op/build db)]

    ;; --- ho-1: full clean lifecycle -----------------------------------
    ;; The intake patch re-states the order's OWN counterparty read back
    ;; out of the store -- a normalization upsert, never a new fact.
    (exec! actor "ho-1-intake"
           {:op :order/intake :subject "ho-1"
            :patch {:id "ho-1"
                    :counterparty (:counterparty (store/household-order db "ho-1"))}})
    (verify+approve! actor "ho-1")
    (dispatch+approve! actor "ho-1")
    (let [tid "ho-1-settle"]
      (exec! actor tid {:op :invoice/settle :subject "ho-1"})
      (approve! actor tid))

    ;; --- ho-2: no spec-basis, then no evidence on file ------------------
    (exec! actor "ho-2-verify" {:op :safety/verify :subject "ho-2"})
    (exec! actor "ho-2-dispatch" {:op :delivery/dispatch :subject "ho-2"})

    ;; --- ho-3 / ho-4 / ho-5: generic counterparty-diligence holds -------
    (doseq [ho-id ["ho-3" "ho-4" "ho-5"]]
      (verify+approve! actor ho-id)
      (exec! actor (str ho-id "-dispatch") {:op :delivery/dispatch :subject ho-id}))

    ;; --- ho-6: a fully certified children's product clears --------------
    (verify+approve! actor "ho-6")
    (dispatch+approve! actor "ho-6")
    (let [tid "ho-6-settle"]
      (exec! actor tid {:op :invoice/settle :subject "ho-6"})
      (approve! actor tid))

    ;; --- ho-7: children's product with no CPC on file -------------------
    (verify+approve! actor "ho-7")
    (exec! actor "ho-7-dispatch" {:op :delivery/dispatch :subject "ho-7"})

    ;; --- ho-8: open recall -> resolved -> dispatches --------------------
    (verify+approve! actor "ho-8")
    (exec! actor "ho-8-dispatch" {:op :delivery/dispatch :subject "ho-8"})
    (exec! actor "ho-8-recall-resolved"
           {:op :order/intake :subject "ho-8"
            :patch {:id "ho-8" :recall-status :resolved}})
    (dispatch+approve! actor "ho-8")

    ;; --- ho-1 again: double-actuation guards ----------------------------
    (exec! actor "ho-1-dispatch-again" {:op :delivery/dispatch :subject "ho-1"})
    (exec! actor "ho-1-settle-again" {:op :invoice/settle :subject "ho-1"})
    {:db db :audit @*audit*}))))

;; ----------------------------- rendering -----------------------------

(defn- esc [v]
  (-> (str v)
      (str/replace "&" "&amp;")
      (str/replace "<" "&lt;")
      (str/replace ">" "&gt;")))

(defn- kw-name [v] (if (keyword? v) (name v) (str v)))

(defn- holds [ledger] (filter #(= :governor-hold (:t %)) ledger))

;; --- household-orders ------------------------------------------------

(defn- last-fact-for [ledger ho-id]
  (last (filter #(= (:subject %) ho-id) ledger)))

(defn- status-cell [ledger ho-id]
  (let [f (last-fact-for ledger ho-id)]
    (cond
      (nil? f) "<span class=\"muted\">no activity</span>"
      (= :governor-hold (:t f))
      (str "<span class=\"critical\">HARD hold &middot; "
           (esc (str/join ", " (map kw-name (:basis f)))) "</span>")
      (= :committed (:t f)) "<span class=\"ok\">committed</span>"
      :else "<span class=\"muted\">in progress</span>")))

(defn- lifecycle-cell [{:keys [dispatched? invoiced? dispatch-number invoice-number]}]
  (cond
    invoiced? (str "<span class=\"ok\">dispatched &amp; invoiced</span> <code>"
                   (esc dispatch-number) "</code> <code>" (esc invoice-number) "</code>")
    dispatched? (str "<span class=\"warn\">dispatched, not yet invoiced</span> <code>"
                     (esc dispatch-number) "</code>")
    :else "<span class=\"muted\">in the distribution center</span>"))

(defn- product-cell [{:keys [product-category childrens-product? recall-status]}]
  (str "<code>" (esc (kw-name product-category)) "</code>"
       (when childrens-product? " <span class=\"tag\">children's product</span>")
       (when (= :open recall-status) " <span class=\"tag\">recall open</span>")
       (when (= :resolved recall-status) " <span class=\"tag\">recall resolved</span>")))

(defn- order-row [ledger {:keys [id order-id sku counterparty jurisdiction] :as ho}]
  (format "        <tr><td><code>%s</code></td><td>%s</td><td>%s</td><td><code>%s</code></td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>"
          (esc id) (esc order-id) (product-cell ho) (esc sku)
          (esc counterparty) (esc jurisdiction)
          (lifecycle-cell ho)
          (status-cell ledger id)))

;; --- action gate -----------------------------------------------------

(def ^:private gate-ops
  "This actor's closed op contract, in lifecycle order. The gate text
  beside each op is DERIVED from `housewaretrade.phase`/
  `housewaretrade.governor` below, not hand-asserted."
  [:order/intake :safety/verify :delivery/dispatch :invoice/settle])

(defn- gate-row [op]
  (let [{:keys [label writes auto]} (get phase/phases (:phase operator))
        high? (contains? governor/high-stakes op)]
    (format "        <tr><td><code>%s</code></td><td>%s</td><td>%s</td></tr>"
            (esc (str op))
            (cond
              (not (contains? writes op))
              (format "<span class=\"critical\">HOLD &middot; not writable in phase %s (%s)</span>"
                      (esc (:phase operator)) (esc label))
              (contains? auto op)
              (format "<span class=\"ok\">auto-commit when the governor is clean (phase %s %s)</span>"
                      (esc (:phase operator)) (esc label))
              :else
              "<span class=\"warn\">human approval &middot; never in any phase's auto set</span>")
            (if high?
              "<span class=\"critical\">high-stakes</span> &middot; the governor escalates independently of the phase gate"
              (format "governor confidence floor %s" (esc governor/confidence-floor))))))

;; --- HARD rules exercised --------------------------------------------

(defn- rules-exercised
  "Every HARD rule this run actually produced, in first-appearance
  order, with the real violation detail the governor wrote and the real
  subjects it held."
  [ledger]
  (let [vs (for [f (holds ledger) v (:violations f)]
             {:rule (:rule v) :detail (:detail v) :subject (:subject f) :op (:op f)})]
    (->> (distinct (map :rule vs))
         (map (fn [rule]
                (let [hits (filter #(= rule (:rule %)) vs)]
                  {:rule rule
                   :detail (:detail (first hits))
                   :subjects (distinct (map :subject hits))
                   :ops (distinct (map :op hits))}))))))

(defn- rule-row [{:keys [rule detail subjects ops]}]
  (format "        <tr><td><code>:%s</code></td><td>%s</td><td>%s</td><td>%s</td></tr>"
          (esc (kw-name rule))
          (esc (str/join ", " (map str ops)))
          (esc (str/join ", " subjects))
          (esc detail)))

;; --- approver attribution --------------------------------------------

(defn- approval-row [{:keys [op subject by approver-landed]}]
  (format "        <tr><td><code>%s</code></td><td><code>%s</code></td><td>%s</td><td>%s</td></tr>"
          (esc (str op)) (esc subject) (esc by)
          (if approver-landed
            (format "<span class=\"ok\">yes</span> &middot; %s, <code>%s</code> = <code>%s</code>"
                    (esc (:where approver-landed))
                    (esc (:key approver-landed))
                    (esc (:value approver-landed)))
            "<span class=\"warn\">no</span> &middot; nothing this approval wrote to the store carries an approver &mdash; the attribution survives only as the audit fact in this row")))

;; --- jurisdictions ---------------------------------------------------

(defn- jurisdiction-row [iso3]
  (if-let [sb (facts/spec-basis iso3)]
    (format "        <tr><td><code>%s</code></td><td>%s</td><td><code>%s</code></td><td>%s</td></tr>"
            (esc iso3) (esc (:owner-authority sb)) (esc (:provenance sb))
            (esc (str/join "; " (:required-evidence sb))))
    (format "        <tr><td><code>%s</code></td><td colspan=\"3\"><span class=\"critical\">no spec-basis in housewaretrade.facts/catalog</span> &middot; the governor HARD-holds rather than let the advisor invent one</td></tr>"
            (esc iso3))))

;; --- ledger ----------------------------------------------------------

(defn- ledger-detail [{:keys [t basis summary]}]
  (if (= :governor-hold t)
    (str "<code>" (esc (str/join ", " (map kw-name basis))) "</code>")
    (esc summary)))

(defn- ledger-row [{:keys [t op subject disposition] :as f}]
  (format "        <tr><td>%s</td><td><code>%s</code></td><td><code>%s</code></td><td>%s</td><td>%s</td></tr>"
          (if (= :governor-hold t)
            "<span class=\"critical\">governor-hold</span>"
            (str "<span class=\"ok\">" (esc (kw-name t)) "</span>"))
          (esc (str op)) (esc subject) (esc (kw-name disposition))
          (ledger-detail f)))

;; --- registry drafts -------------------------------------------------

(defn- record-row [r]
  (format "        <tr><td><code>%s</code></td><td>%s</td><td><code>%s</code></td><td>%s</td><td>%s</td></tr>"
          (esc (get r "record_id")) (esc (get r "kind"))
          (esc (get r "household_order_id")) (esc (get r "jurisdiction"))
          (if (get r "immutable")
            "<span class=\"ok\">immutable</span>"
            "<span class=\"warn\">mutable</span>")))

(defn render
  "Renders the whole operator-console document from the `{:db :audit}`
  result of `run-demo!` (or any other real scenario)."
  [{:keys [db audit]}]
  (let [ledger (vec (store/ledger db))
        approvals (filter #(= :approval-granted (:t %)) audit)
        orders (store/all-household-orders db)
        hs (holds ledger)
        jurisdictions (sort (distinct (map :jurisdiction orders)))
        records (concat (store/dispatch-history db) (store/invoice-history db))]
    (str
     "<html><head><meta charset=\"utf-8\"><title>cloud-itonami-isic-4649 &middot; housewaretrade</title><style>"
     (jp-go-dds.skin/dds+skin)
     "</style></head><body>\n"
     "<header class=\"bar\">\n"
     "  <h1>Wholesale of other household goods (ISIC 4649) — Operator Console</h1>\n"
     "  <span class=\"badge\">read-only sample · governor-gated · dispatch and invoice settlement are always a human call</span>\n"
     "</header>\n"
     "<main>\n"

     "  <section class=\"card\">\n"
     "    <h2>Household-orders</h2>\n"
     "    <p class=\"muted\">Build-time snapshot — generated by <code>housewaretrade.render-html</code> (<code>clojure -M:dev:render-html</code>) by running <code>housewaretrade.operation</code> → <code>housewaretrade.governor</code> → <code>housewaretrade.store</code> over the seeded order set. Every value below is read back out of the store after the run.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>ID</th><th>Order</th><th>Product</th><th>SKU</th><th>Counterparty</th><th>Jurisdiction</th><th>Dispatch / invoice</th><th>Last governor disposition</th></tr></thead>\n"
     "      <tbody>\n"
     (str/join "\n" (map (partial order-row ledger) orders)) "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"

     "  <section class=\"card\">\n"
     "    <h2>Action gate (Consumer Product Safety Governor + phase " (esc (:phase operator)) ")</h2>\n"
     "    <p class=\"muted\">Derived from <code>housewaretrade.phase/phases</code> and <code>housewaretrade.governor/high-stakes</code>. HARD violations are never overridable and never reach a human approver; <code>:delivery/dispatch</code> and <code>:invoice/settle</code> are absent from every phase's auto set, and the governor escalates on them independently — two layers agree.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Op</th><th>Phase gate</th><th>Governor gate</th></tr></thead>\n"
     "      <tbody>\n"
     (str/join "\n" (map gate-row gate-ops)) "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"

     "  <section class=\"card\">\n"
     "    <h2>HARD holds this run produced (" (count hs) ")</h2>\n"
     "    <p class=\"muted\">One row per distinct rule the governor actually fired during this run. The detail column is the governor's own violation text, verbatim.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Rule</th><th>Op(s)</th><th>Order(s) held</th><th>Governor detail</th></tr></thead>\n"
     "      <tbody>\n"
     (str/join "\n" (map rule-row (rules-exercised ledger))) "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"

     "  <section class=\"card\">\n"
     "    <h2>Approver attribution (" (count approvals) " approvals granted this run)</h2>\n"
     "    <p class=\"muted\">Every <code>:approval-granted</code> fact this run produced. The last column is <em>measured</em>, not asserted: the generator snapshots the whole store immediately before and after each approval and searches only the artifacts <em>that approval itself changed</em> for an approver-shaped key. (A point-in-time probe would be wrong here — by the time <code>ho-1</code>'s dispatch is approved, its safety assessment already carries <code>:approved-by</code> from the earlier <code>:safety/verify</code> approval, and would falsely credit the dispatch.) <strong>Known scaffold defect, stated plainly:</strong> <code>housewaretrade.operation</code>'s <code>:request-approval</code> node attaches the approver to the record under <code>:payload</code>, but <code>housewaretrade.store/commit-record!</code> only reads <code>:payload</code> for the <code>:safety-assessment/set</code> effect — <code>:order/upsert</code> writes <code>:value</code> (no approver) and <code>:order/mark-dispatched</code>/<code>:order/mark-invoiced</code> derive their patch from the store and read neither. So a safety verification carries its approver into the SSoT and a dispatch or an invoice settlement does not. This console will not print an approver the store does not hold; for those rows the attribution exists only as the audit fact itself, which is <em>not</em> in the append-only ledger below.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Op</th><th>Order</th><th>Approved by (resume payload)</th><th>Did this approval put the approver on the SSoT?</th></tr></thead>\n"
     "      <tbody>\n"
     (str/join "\n" (map approval-row approvals)) "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"

     "  <section class=\"card\">\n"
     "    <h2>Jurisdiction spec-basis</h2>\n"
     "    <p class=\"muted\">The jurisdictions the seeded orders actually reference, looked up in <code>housewaretrade.facts/catalog</code>. A jurisdiction with no entry has no spec-basis at all — the advisor must not invent one, and the governor holds if it tries.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>ISO3</th><th>Owner authority</th><th>Provenance</th><th>Required evidence</th></tr></thead>\n"
     "      <tbody>\n"
     (str/join "\n" (map jurisdiction-row jurisdictions)) "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"

     "  <section class=\"card\">\n"
     "    <h2>Audit ledger (this run — " (count ledger) " facts)</h2>\n"
     "    <p class=\"muted\">Append-only decision-fact log. Only the <code>:commit</code> and <code>:hold</code> nodes of the StateGraph write here; the advisor's own proposal traces stay in the run's audit channel and never touch the SSoT.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Fact</th><th>Op</th><th>Order</th><th>Disposition</th><th>Basis / summary</th></tr></thead>\n"
     "      <tbody>\n"
     (str/join "\n" (map ledger-row ledger)) "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"

     "  <section class=\"card\">\n"
     "    <h2>Registry drafts (" (count records) ")</h2>\n"
     "    <p class=\"muted\">The dispatch and invoice records <code>housewaretrade.registry</code> constructed for the commits above. Drafts — every certificate this actor produces is unsigned; signature is the operator's act.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Record</th><th>Kind</th><th>Order</th><th>Jurisdiction</th><th>Status</th></tr></thead>\n"
     "      <tbody>\n"
     (str/join "\n" (map record-row records)) "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"

     "</main>\n"
     "</body></html>\n")))

(defn -main [& args]
  (let [out (or (first args) "docs/samples/operator-console.html")
        {:keys [db audit] :as run} (run-demo!)
        ledger (vec (store/ledger db))
        hs (holds ledger)]
    (when (empty? hs)
      (throw (ex-info "no :governor-hold fact on the ledger — refusing to write a console that shows no real hold"
                      {:ledger-facts (count ledger)})))
    (spit out (render run))
    (println "wrote" out "(" (count ledger) "ledger facts,"
             (count hs) "HARD holds,"
             (count (filter #(= :approval-granted (:t %)) audit)) "approvals,"
             (count (store/dispatch-history db)) "dispatch drafts,"
             (count (store/invoice-history db)) "invoice drafts )")))
